export type ClipRect = { x: number; y: number; width: number; height: number; matrix?: number[] };
export type GradientStop = { offset: number; color: string; opacity?: number };
export type Gradient = { type: "linear"; units: "objectBoundingBox" | "userSpaceOnUse"; x1: number; y1: number; x2: number; y2: number; transform?: number[]; stops: GradientStop[] };
const color = /^(#[0-9a-f]{3,8}|[a-z]+|rgba?\([\d\s.,%]+\)|hsla?\([\d\s.,%]+\))$/i;
const finite = (v: unknown): v is number => typeof v === "number" && Number.isFinite(v);
export function validateStyle(p: Record<string, unknown>) {
  if (p.strokeDashoffset !== undefined && (!finite(p.strokeDashoffset) || Math.abs(Number(p.strokeDashoffset)) > 1e9)) throw new Error("strokeDashoffset must be finite and bounded.");
  for (const k of ["fillOpacity", "strokeOpacity"])
    if (p[k] !== undefined && (!finite(p[k]) || Number(p[k]) < 0 || Number(p[k]) > 1)) throw new Error(`${k} must be between 0 and 1.`);
  if (p.strokeDasharray !== undefined && (!Array.isArray(p.strokeDasharray) || p.strokeDasharray.length > 256 || p.strokeDasharray.some(v => !finite(v) || v < 0))) throw new Error("strokeDasharray must contain finite nonnegative numbers.");
  for (const k of ["strokeLinecap", "strokeLinejoin", "fillRule", "fontStyle"])
    if (p[k] !== undefined && typeof p[k] !== "string") throw new Error(`${k} must be text.`);
  if (p.strokeLinecap !== undefined && !["butt", "round", "square"].includes(String(p.strokeLinecap))) throw new Error("Invalid strokeLinecap.");
  if (p.strokeLinejoin !== undefined && !["miter", "round", "bevel"].includes(String(p.strokeLinejoin))) throw new Error("Invalid strokeLinejoin.");
  if (p.fillRule !== undefined && !["nonzero", "evenodd"].includes(String(p.fillRule))) throw new Error("Invalid fillRule.");
  if (p.fontStyle !== undefined && !["normal", "italic", "oblique"].includes(String(p.fontStyle))) throw new Error("Invalid fontStyle.");
  if (p.fontFamily !== undefined && (typeof p.fontFamily !== "string" || !p.fontFamily.trim() || p.fontFamily.length > 256 || /[\u0000-\u001f<>]/.test(p.fontFamily))) throw new Error("Invalid fontFamily.");
  if (p.clipRects !== undefined) { if (!Array.isArray(p.clipRects) || p.clipRects.length > 32) throw new Error("clipRects must be an array of at most 32 rectangles."); for (const c of p.clipRects as ClipRect[]) { if (!c || ![c.x,c.y,c.width,c.height].every(finite) || c.width < 0 || c.height < 0 || (c.matrix !== undefined && (!Array.isArray(c.matrix) || c.matrix.length !== 6 || c.matrix.some(v=>!finite(v)))) ) throw new Error("Invalid clip rectangle."); } }
  if (p.fillGradient !== undefined || p.strokeGradient !== undefined) for (const k of ["fillGradient", "strokeGradient"]) { const g=p[k] as Gradient; if(g!==undefined && (!g || g.type!=="linear" || !["objectBoundingBox","userSpaceOnUse"].includes(g.units) || ![g.x1,g.y1,g.x2,g.y2].every(finite) || (g.transform!==undefined && (g.transform.length!==6 || g.transform.some(v=>!finite(v)))) || !Array.isArray(g.stops) || !g.stops.length || g.stops.length>32 || g.stops.some(s=>!finite(s.offset)||s.offset<0||s.offset>1||typeof s.color!=="string"||!color.test(s.color)||(s.opacity!==undefined&&(!finite(s.opacity)||s.opacity<0||s.opacity>1))))) throw new Error(`Invalid ${k}.`); }
}
export function styleAttrs(p: Record<string, any>): Record<string,string> { validateStyle(p); const a:Record<string,string>={fill:p.fill??"none",stroke:p.stroke??"none","stroke-width":String(p.strokeWidth??0),opacity:String(p.opacity??1)}; if(p.strokeDasharray)a["stroke-dasharray"]=p.strokeDasharray.join(" "); if(p.strokeDashoffset!==undefined)a["stroke-dashoffset"]=String(p.strokeDashoffset); for(const k of ["strokeLinecap","strokeLinejoin","fillRule","fontStyle","fillOpacity","strokeOpacity"]){const attr=k.replace(/[A-Z]/g,m=>`-${m.toLowerCase()}`); if(p[k]!==undefined)a[attr]=String(p[k]);} return a; }
export function gradientDefs(id:string,p:Record<string,any>):string { let out=""; for(const kind of ["fillGradient","strokeGradient"]){const g=p[kind] as Gradient|undefined;if(!g)continue;out+=`<linearGradient id="${id}-${kind}" gradientUnits="${g.units}" x1="${g.x1}" y1="${g.y1}" x2="${g.x2}" y2="${g.y2}"${g.transform?` gradientTransform="matrix(${g.transform.join(" ")})"`:""}>${g.stops.map(s=>`<stop offset="${s.offset}" stop-color="${s.color}" stop-opacity="${s.opacity??1}"/>`).join("")}</linearGradient>`;}return out; }
export function clipStyle(id:string,p:Record<string,any>):{defs:string;attr:string}{const cs=p.clipRects as ClipRect[]|undefined;if(!cs?.length)return {defs:"",attr:""};let defs="",previous="";cs.forEach((c,i)=>{const current=`${id}-clip-${i}`;const rect=`<rect x="${c.x}" y="${c.y}" width="${c.width}" height="${c.height}"${c.matrix?` transform="matrix(${c.matrix.join(" ")})"`:""}/>`;defs+=previous?`<clipPath id="${current}"><g clip-path="url(#${previous})">${rect}</g></clipPath>`:`<clipPath id="${current}">${rect}</clipPath>`;previous=current;});return {defs,attr:` clip-path="url(#${previous})"`};}
